module.exports = {
  /**腾讯地图key */
  Map_Key: 'GKSBZ-OK33D-TQF4Y-HJDZX-KQEE6-GGFRZ',
  /** 全局常量*/
  AppTitle: '喵姐米粉',
  AppDesc: '最正宗的南充米粉，小时候的味道!',
  LoadingTitle: '加载中...',
  /**swiper相关 */
  IndicatorDots: true,
  Autoplay: true,
  Interval: 3000,
  Duration: 1000,
  /**图片地址 */
  ico_zb: 'static/images/zb.png',
  ico_phone: 'static/images/phone.png',
  ico_time: 'static/images/time.png',
  ico_picture: 'static/images/picture.png',
  ico_notice: 'static/images/notice.png',
  img_call: 'static/images/call.png',
  img_mina: 'static/images/mina.png',
  img_first: 'static/images/first.png',
  img_drop: 'static/images/drop.png',
  ico_logo: 'static/images/logo.png',
  ico_share: 'static/images/share.png',
  ico_clear: 'static/images/clear.png',
  img_wechat: 'static/images/wechat.png',
  img_cart: 'static/images/cart.png',
  img_cartt: 'static/images/cartt.png',
  img_rightnav: 'static/images/rightnav.png',
  /**页面标题 */
  PageTitle_Pictures: "店铺图片",
  PageTitle_Location: "地图位置",
  PageTitle_GoodsDetail: "详情",
  PageTitle_Account: "确认订单",
  /**缺省设置 */
  img_fail: 'static/images/fail.png',
  img_default: 'static/images/default.png',
  title_default: '店铺名称',
  address_default: '店铺未标注地址',
  phone_default: '商家未预留电话',
  time_default: '请联系店家',
  notice_default: '暂无公告',
  title_default: '店铺名称',
  /**提示信息 */
  Msg_DataError:'获取数据失败',
  Msg_AddrError: '获取地址失败',
  Msg_PhoneError: '拨打电话失败',
  Msg_WxAddrError: '获取收货地址失败',
  /**缓存名称 */
  Storage_StoreInfo: 'storeInfo',
  Storage_UserLocation: 'userLocationInfo',
  /**授权范围 */
  Scope_UserLocation: 'scope.userLocation',
  /**页面地址 */
  AppHome: '/pages/index/index',
  PagePath_Sell: '/pages/sell/sell',
  PagePath_GoodsDetail: '/pages/sell/good/good',
  PagePath_Account: '/pages/sell/account/account'
};